import numpy as np
creat1_numpyArray=np.array([1,0,0,8,6])
creat2_numpyArray=np.array([[1,2,3],[3,2,1]])
creat3_numpyArray=np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
creat4_numpyArray=np.arange(1,7)
creat5_numpyArray=np.linspace(0,11,12)
creat6_numpyArray=creat4_numpyArray.reshape(2,3)
creat7_numpyArray=creat5_numpyArray.reshape(3,4)
print(creat1_numpyArray,'\n它的轴为',creat1_numpyArray.ndim,';维度为：',creat1_numpyArray.shape,';元素个数为：',creat1_numpyArray.size)
print(creat2_numpyArray,'\n它的轴为',creat2_numpyArray.ndim,';维度为：',creat2_numpyArray.shape,';元素个数为：',creat2_numpyArray.size)
print(creat3_numpyArray,'\n它的轴为',creat3_numpyArray.ndim,';维度为：',creat3_numpyArray.shape,';元素个数为：',creat3_numpyArray.size)
print(creat4_numpyArray,'\n它的轴为',creat4_numpyArray.ndim,';维度为：',creat4_numpyArray.shape,';元素个数为：',creat4_numpyArray.size)
print(creat5_numpyArray,'\n它的轴为',creat5_numpyArray.ndim,';维度为：',creat5_numpyArray.shape,';元素个数为：',creat5_numpyArray.size)
print(creat6_numpyArray,'\n它的轴为',creat6_numpyArray.ndim,';维度为：',creat6_numpyArray.shape,';元素个数为：',creat6_numpyArray.size)
print(creat7_numpyArray,'\n它的轴为',creat7_numpyArray.ndim,';维度为：',creat7_numpyArray.shape,';元素个数为：',creat7_numpyArray.size)